DROP TABLE user IF EXISTS;
CREATE TABLE user(
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR(64),
    name        VARCHAR(32),
    age         INT(3),
    balance     DECIMAL(10, 2),
    PRIMARY KEY (id)
);
